### ISSUE TITLE
How to set the themeSystem setting to bootstrap?

### ISSUE THREAD

**Issue by rohitkrishna094** [sanjeev07/fullcalendar-reactWrapper#19]
The original fullCalender provides an option to set the theme to be bootstrap.

Here is the link [Full Calendar themeSystem](https://fullcalendar.io/docs/themeSystem)

How to achieve this in fullcalendar-reactWrapper? Is there a prop to do that?

**Comment by pierroberto** [comment]
Did you try to add the option `<Fullcalendar themeSystem="bootstrap" />`?
All the props you pass should be added in the configs of fullcalendar.
