### ISSUE TITLE
How to call mousehover event 

### ISSUE THREAD

**Issue by ignivamonikarani** [sanjeev07/fullcalendar-reactWrapper#2]
Please provide a workAround for handle the mouse hover event with react js.

**Comment by sanjeev07** [comment]
i guess your question is , how to handle eventMouseover .
(https://fullcalendar.io/docs/mouse/eventMouseover/)
if so then please follow the below steps :- 
`<FullCalendar
        eventMouseover={this.handleMouseOver.bind(this)}
/>`
handleMouseOver function will Triggered when the user mouses over an event.
