### ISSUE TITLE
"locale" directive does not work

### ISSUE THREAD

**Issue by ByronChang** [sanjeev07/fullcalendar-reactWrapper#4]
does not function for buttons in header like: 'month, agendaWeek, agendaDay, listMonth'

**Comment by sanjeev07** [comment]
try using something like :- 
<FullCalendar
     header = {{
			        	left: 'prev,next,
			        	center: 'title',
			        	right: 'month, agendaWeek , agendaWeek ,listMonth'
			    	}}
/>  
it should work . if it won't let me know .

**Comment by sanjeev07** [comment]
i have try it, adding locale option, then also it worked .  in case if it is not working when you used locale option. you can share what you have tried .

**Comment by husamettinor** [comment]
Same thing happened to me. I have the following render() function: 

    render() {
        const options = {
		header: {
			left: 'title',
			center: '',
                        right: 'today prev,next'
            },
            defaultView: 'month',
            locale: 'tr',
            events: this.state.events
        }

        return (
            <div>
                <div>
                    <FullCalendar {...options}/>
                </div>
            </div>
        );
    }



I'm trying to translate to Turkish. It works for title but nothing happens for buttons. I had a look at the lib/index.js file and cannot see any localization for buttons.

**Comment by sanjeev07** [comment]
Hi husamettinor, 
actually based on full calendar documentation, the text in buttons, as defined by header . but there is way to change the text to respective locale language as well .i will look into it, and will notify you soon . 
thanks for your comment .

**Comment by husamettinor** [comment]
Hi, 
I added buttonText to props that I gave to component as

`<FullCalendar buttonText={ today: 'bugün', week:'hafta' } />`

and problem is solved.
