### ISSUE TITLE
prev next button events 

### ISSUE THREAD

**Issue by JesusFregoso** [sanjeev07/fullcalendar-reactWrapper#6]
how can i handle the click event in prev and next button ??

**Comment by sanjeev07** [comment]
there are two way you can handle click event on click of prev and next button . 
1) using with an external button :-  define your custom prev/next button like below code segment . 
 `header: {
	left: 'month,basicWeek,basicDay,listMonth',
	center: 'title',
        right: 'customPrevButton,customNextButton today'
   },
customButtons: {
       customPrevButton: {
                text: 'prev',
                click: function () {
	               console.log('prev')
                  }
       },
       customNextButton: {
	         text: 'next!',
	         click: function () {
	               console.log('next')
	         }
        }
},`

2) the best way is using  "viewRender" use viewRender as below code segment 
`viewRender: (view, element)=> {
             console.log(view,element)
 }` 
this will capture all the click event of the header button .

**Comment by JesusFregoso** [comment]
thanks that really help  i used the second one i think it has a better aproach.

**Comment by Bakushin10** [comment]
@sanjeev07 Could you please elaborate on how I can use `viewRender: (view, element)=> { console.log(view,element) }` ?? maybe show me the par t of the code ? Thank you !
