### ISSUE TITLE
How do we call methods on the calendar?

### ISSUE THREAD

**Issue by cjmyles** [sanjeev07/fullcalendar-reactWrapper#7]
I would like to call the [events refetch method](https://fullcalendar.io/docs/refetchEvents) on the calendar. Is there a way to do this? Thanks.

**Comment by sanjeev07** [comment]
i guess your issue is similar to [https://github.com/sanjeev07/fullcalendar-reactWrapper/issues/1](url)
can you go through it once .

**Comment by cjmyles** [comment]
Hi @sanjeev07, thank you for the prompt response. This makes perfect sense!
